### ISSUE TITLE
Merge ID to master

### ISSUE THREAD

**Issue by DUFCLiam** [PluginService/BasicEssentials#5]
@AvalancheYT, May I do this?

**Comment by AvalancheYT** [comment]
NOT YET! It is still bleeding...

**Comment by DUFCLiam** [comment]
Ok. @AvalancheYT May I merge it to my development?

**Comment by AvalancheYT** [comment]
If you want...
Please note, I am working on player system.

**Comment by DUFCLiam** [comment]
I know die to #2
